// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.osrce.sitrep.domain;

import com.osrce.sitrep.domain.Entity;
import javax.persistence.Table;

privileged aspect Entity_Roo_Jpa_Entity {
    
    declare @type: Entity: @javax.persistence.Entity;
    
    declare @type: Entity: @Table(schema = "public", name = "entity");
    
}
