// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.osrce.sitrep.domain;

import com.osrce.sitrep.domain.SpatialRefSys;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect SpatialRefSys_Roo_Configurable {
    
    declare @type: SpatialRefSys: @Configurable;
    
}
