// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.osrce.sitrep.domain;

import com.osrce.sitrep.domain.SpatialRefSys;

privileged aspect SpatialRefSys_Roo_JavaBean {
    
    public Integer SpatialRefSys.getSrid() {
        return this.srid;
    }
    
    public void SpatialRefSys.setSrid(Integer srid) {
        this.srid = srid;
    }
    
}
