// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.osrce.sitrep.domain;

import com.osrce.sitrep.domain.SrAssetsStatus;

privileged aspect SrAssetsStatus_Roo_JavaBean {
    
    public Integer SrAssetsStatus.getId() {
        return this.id;
    }
    
    public void SrAssetsStatus.setId(Integer id) {
        this.id = id;
    }
    
}
