// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.osrce.sitrep.domain;

import com.osrce.sitrep.domain.SrGroups;

privileged aspect SrGroups_Roo_JavaBean {
    
    public Integer SrGroups.getGid() {
        return this.gid;
    }
    
    public void SrGroups.setGid(Integer gid) {
        this.gid = gid;
    }
    
}
