// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.osrce.sitrep.domain;

import com.osrce.sitrep.domain.SrLocations;
import javax.persistence.Entity;
import javax.persistence.Table;

privileged aspect SrLocations_Roo_Jpa_Entity {
    
    declare @type: SrLocations: @Entity;
    
    declare @type: SrLocations: @Table(schema = "public", name = "sr_locations");
    
}
