// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.osrce.sitrep.domain;

import com.osrce.sitrep.domain.SrLocationsWorkqueue;

privileged aspect SrLocationsWorkqueue_Roo_JavaBean {
    
    public Integer SrLocationsWorkqueue.getId() {
        return this.id;
    }
    
    public void SrLocationsWorkqueue.setId(Integer id) {
        this.id = id;
    }
    
}
