// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.osrce.sitrep.domain;

import com.osrce.sitrep.domain.SrModules;

privileged aspect SrModules_Roo_JavaBean {
    
    public Integer SrModules.getId() {
        return this.id;
    }
    
    public void SrModules.setId(Integer id) {
        this.id = id;
    }
    
}
