// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.osrce.sitrep.domain;

import com.osrce.sitrep.domain.SrQueries;

privileged aspect SrQueries_Roo_JavaBean {
    
    public Integer SrQueries.getId() {
        return this.id;
    }
    
    public void SrQueries.setId(Integer id) {
        this.id = id;
    }
    
}
