// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.osrce.sitrep.domain;

import com.osrce.sitrep.domain.SrQueryMonitorResults;

privileged aspect SrQueryMonitorResults_Roo_JavaBean {
    
    public Long SrQueryMonitorResults.getId() {
        return this.id;
    }
    
    public void SrQueryMonitorResults.setId(Long id) {
        this.id = id;
    }
    
}
