// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.osrce.sitrep.domain;

import com.osrce.sitrep.domain.SrQueryMonitor;

privileged aspect SrQueryMonitor_Roo_JavaBean {
    
    public Long SrQueryMonitor.getId() {
        return this.id;
    }
    
    public void SrQueryMonitor.setId(Long id) {
        this.id = id;
    }
    
}
