// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.osrce.sitrep.domain;

import com.osrce.sitrep.domain.SrSession;

privileged aspect SrSession_Roo_JavaBean {
    
    public String SrSession.getId() {
        return this.id;
    }
    
    public void SrSession.setId(String id) {
        this.id = id;
    }
    
}
