// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.osrce.sitrep.domain;

import com.osrce.sitrep.domain.SrStylePresets;

privileged aspect SrStylePresets_Roo_JavaBean {
    
    public Integer SrStylePresets.getId() {
        return this.id;
    }
    
    public void SrStylePresets.setId(Integer id) {
        this.id = id;
    }
    
}
