// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.osrce.sitrep.domain;

import com.osrce.sitrep.domain.SrStyleSymbolizers;

privileged aspect SrStyleSymbolizers_Roo_JavaBean {
    
    public Integer SrStyleSymbolizers.getId() {
        return this.id;
    }
    
    public void SrStyleSymbolizers.setId(Integer id) {
        this.id = id;
    }
    
}
