// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.osrce.sitrep.domain;

import com.osrce.sitrep.domain.SrStyles;

privileged aspect SrStyles_Roo_JavaBean {
    
    public Integer SrStyles.getId() {
        return this.id;
    }
    
    public void SrStyles.setId(Integer id) {
        this.id = id;
    }
    
}
