// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.osrce.sitrep.domain;

import com.osrce.sitrep.domain.SrWindowLayout;

privileged aspect SrWindowLayout_Roo_JavaBean {
    
    public Integer SrWindowLayout.getId() {
        return this.id;
    }
    
    public void SrWindowLayout.setId(Integer id) {
        this.id = id;
    }
    
}
